services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbuser
      POSTGRES_DB: doctorsdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    command: npm run dev
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - ./.env

